# Drugstore Fachklassen

Erster Wurf, kein korrektes UML

@startuml

object Fachkraft
object Abgabe
object Patientenschaft
object Bestandeskontrolle
object Abteilungsapotheke
object Substanz

Fachkraft -right- Abgabe: > erfasst
Abgabe -right- Patientenschaft: > geht an
Abgabe -down- Substanz: > enthält

Abteilungsapotheke -right- Substanz: enthält
Fachkraft -down- Bestandeskontrolle: > kontrolliert/\n> signiert/\n> exportiert

Bestandeskontrolle -- Abteilungsapotheke: > verwendet
Bestandeskontrolle -- Substanz: > enthält

Fachkraft -- Abteilungsapotheke: > verwaltet
Fachkraft -- Substanz: > erstellt/\n> bearbeitet/\n> entfernt

Fachkraft : Name
Abgabe : Dosis
Patientenschaft : Name
Bestandeskontrolle : Substanzanzahl
Abteilungsapotheke : Bestand
Substanz : Name
Substanz : Dosierung
Substanz : Kategorie
Substanz : Ausgabe-Einheit
Substanz : Toleranz

@enduml
