@startuml class-diagram

actor "User" as user

node "Drugstore App" {
    package Presentation {
      component View {
        component Activity
        component Fragment
        component Adapter
      }
      component ViewModel
      Activity -down-> Fragment
      Fragment  -down-> Adapter
      View  -down-> ViewModel
    }

    package Domain {
      component "Use Case" as uc
      component Service
      uc -down-> Service
    }

    package Data {
      component Repository
      component Entity
      component DAO
      database Database
      Repository --> DAO
      DAO -down-> Database
      DAO -right-> Entity
    }
}

user -down-> View
ViewModel -down-> uc
Service -down-> Repository

@enduml