@startuml class-diagram

actor "User" as user

interface "External Services" as e #lightgrey

node "Drugstore" {
    package Presentation {
      component View {
        component Activity
        component Fragment
        component Adapter
      }
      component ViewModel
      Activity -down-> Fragment
      Fragment  -down-> Adapter
      View  -down-> ViewModel
    }

    package Domain {
      component "Use Case" as uc
      component Service
      uc -down-> Service
    }

    package Data {
      component Repository
      component Entity
      component DAO
      component Provider
      database Database
      Repository --> Provider
      Repository --> DAO
      DAO -down-> Database
      DAO --> Entity
      Provider --> Entity
    }
}

user -down-> View
ViewModel -down-> uc
Service -down-> Repository
Provider .down.> e

@enduml