@startuml usecase-overview
left to right direction
node Drugstore {

    node System {
        usecase "Benutzer Registrierung" as UC11
        usecase "Benutzer Login" as UC12
        usecase "Benutzer Logout" as UC13
        usecase "Externe Sicherung der Datenbank" as UC14
        usecase "Wiederherstellung aus externer Sicherung" as UC15
    }

    node Medikamentenverwaltung {
        usecase "Medikament erfassen" as UC21
        usecase "Medikament bearbeiten" as UC22
        usecase "Medikament löschen" as UC23
        usecase "Medikamente anzeigen" as UC24
        usecase "Medikament Bestand ändern" as UC25
        usecase "Medikament zu Favoriten hinzufügen" as UC26
    }

    node Medikamentabgabe {
        usecase "Medikamentabgabe erfassen" as UC31
        usecase "Medikamente suchen" as UC32
        usecase "Medikamente filtern" as UC33
        usecase "Patient suchen" as UC34
        usecase "Abgabe Verlauf anzeigen" as UC35
        usecase "Abgabe Verlauf filtern" as UC36
    }

    node Bestandeskontrolle {
        usecase "Bestand laden" as UC41
        usecase "Medikament hinzufügen / entfernen" as UC42
        usecase "Signieren" as UC43
        usecase "Verlauf anzeigen" as UC44
        usecase "Verlauf filtern" as UC45
        usecase "Exportieren der Bestandeskontrolle" as UC46
    }
}


:User: - UC11
:User: - UC12
:User: - UC13
:User: - UC14
:User: - UC15

:User: -- UC21
:User: -- UC22
:User: -- UC23
:User: -- UC24
:User: -- UC25
:User: -- UC26

:User: --- UC31
:User: --- UC35

:User: --- UC41
:User: --- UC42
:User: --- UC43
:User: --- UC44
:User: --- UC46

UC22 <- "<<generalizes>>" UC25

UC31 .> "<<include>>" UC25

UC31 ..> "<<include>>" UC32
UC31 ..> "<<include>>" UC34
UC32 ..> "<<include>>" UC33
UC35 ..> "<<include>>" UC36

UC44 ..> "<<include>>" UC45

@enduml