@startuml usecase-overview
left to right direction
node Drugstore {

     node System {
        usecase "Benutzer Registrierung" as UC11
        usecase "Benutzer Login" as UC12
        usecase "Benutzer Logout" as UC13
        usecase "Externe Sicherung der Datenbank" as UC14
        usecase "Wiederherstellung aus externer Sicherung" as UC15
    }

}

:User: -- UC11
:User: -- UC12
:User: -- UC13
:User: -- UC14
:User: -- UC15


@enduml
