@startuml usecase-overview
left to right direction
node Drugstore {

    node Bestandeskontrolle {
        usecase "Bestandeskontrolle starten" as UC41
        usecase "Bestandeskontrolle signieren" as UC42
        usecase "Exportieren der Bestandeskontrolle" as UC43
        usecase "Bestandeskontrolle Verlauf anzeigen" as UC44
        usecase "Bestandeskontrolle Verlauf filtern" as UC45
    }
}
:User: --> UC41
:User: --> UC44

UC41 --> UC42
UC42 ..> UC43
UC44 ..> UC45

@enduml