@startuml usecase-overview
left to right direction
node Drugstore {

    node Bestandeskontrolle {
        usecase "Bestand laden" as UC41
        usecase "Medikament hinzufügen / entfernen" as UC42
        usecase "Signieren" as UC43
        usecase "Verlauf anzeigen" as UC44
        usecase "Verlauf filtern" as UC45
        usecase "Exportieren der Bestandeskontrolle" as UC46
    }
}

:User: --- UC41
:User: --- UC42
:User: --- UC43
:User: --- UC44
:User: --- UC46

UC44 ..> "<<include>>" UC45

@enduml