@startuml data-model-overview

database drugstore {
  object drugs
  object stock
  object transaction
  object user

}

drugs ||..|{ transaction
stock ..> transaction

note left of transaction
  contains histories of:
  - dispensation
  - stock-control
end note

@enduml